# -*- coding: utf-8 -*-
"""Team 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19IU9ioK5QwylJnHPOioWWy_zvFVivImZ
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import nltk
nltk.download('punkt')

from google.colab import drive
drive.mount('/content/gdrive')

data = pd.read_csv('/content/gdrive/MyDrive/complaints.csv')

data.head()

data.shape

#Checking data types throughout data set
data.info()

data.isnull().sum()

#Fixing null values
data = data.fillna('')
data.isnull().sum()

"""Step 1: Basic Analysis

---



---


"""

data['Company'].isna()

###FOR RUNNING PURPOSES ONLY
data = data.sample(n=1000)

complaints_by_bank = data['Complaint ID'].groupby(data['Company']).count().reset_index(name = 'complaint_count')
complaints_by_bank = complaints_by_bank.sort_values(by='complaint_count', ascending=False)
print(complaints_by_bank)

complaints_by_product = data['Complaint ID'].groupby(data['Product']).count().reset_index(name = 'complaint_count')
complaints_by_product = complaints_by_product.sort_values(by='complaint_count', ascending=False)
print(complaints_by_product)

df = pd.DataFrame(data)

dfcb = pd.DataFrame(complaints_by_bank)
dfcb[:10].plot.bar(x='Company', y = 'complaint_count')

dfcp = pd.DataFrame(complaints_by_product)
dfcp[:10].plot.bar(x = 'Product', y = 'complaint_count')

#TOP PRODUCT COMPLAINTS PER COMPANY
for comp in complaints_by_bank['Company'][:10]:
    dfcopy = df.query('Company == @comp')
    complaints_by_product_per_comp = dfcopy['Complaint ID'].groupby(dfcopy['Product']).count().reset_index(name = 'complaint_count')
    complaints_by_product_per_comp = complaints_by_product_per_comp.sort_values(by='complaint_count', ascending=False)
    print(comp +":\n")
    print(complaints_by_product_per_comp[:5])
    print("\n")

#Top Product Complaints for Citi
dfcopy = df.query('Company == "CITIBANK, N.A."')
citi_complaints_by_product = dfcopy['Complaint ID'].groupby(dfcopy['Product']).count().reset_index(name = 'complaint_count')
citi_complaints_by_product = citi_complaints_by_product.sort_values(by='complaint_count', ascending=False)
print("CITIBANK, N.A." +":\n")
print(citi_complaints_by_product[:10])
dfciti = pd.DataFrame(citi_complaints_by_product)
dfciti[:10].plot.bar(x='Product', y = 'complaint_count')

#Checking timeliness of responses for the top 10 banks
for comp in complaints_by_bank['Company'][:10]:
  dfcopy = df.query('Company == @comp')
  dfcopy1 = dfcopy.query('`Timely response?` == "Yes"')
  size1 = dfcopy1.size
  print(comp + " Timely Responses:")
  print(size1)
  dfcopy2 = dfcopy.query('`Timely response?` != "Yes"')
  size2 = dfcopy2.size
  print(comp + " Untimely Responses:")
  print(size2)
  labels = comp + ' Timely Responses', comp + ' Untimely Responses'
  sizes = [size1, size2]
  fig, ax = plt.subplots()
  print(comp)
  ax.pie(sizes, labels=labels)

#Distribution of complaints per bank
top20 = complaints_by_bank['Company'][:20]
complaints_by_bank.loc[~complaints_by_bank['Company'].isin(top20), 'Company'] = 'Other'
complaints_by_bank.groupby(complaints_by_bank['Company'])
labels = complaints_by_bank["Company"][:10]
values = complaints_by_bank["complaint_count"][:10]
fig, ax = plt.subplots()
ax.pie(values, labels=labels, autopct='%1.1f%%')

#Distribution of complaints per product
top10 = complaints_by_product['Product'][:10]
complaints_by_product.groupby(complaints_by_product['Product'])
labels = top10
prod_values = complaints_by_product["complaint_count"][:10]
fig, ax = plt.subplots()
ax.pie(prod_values, labels=labels, autopct='%1.1f%%')

"""Step 2: Text Preparation and Pre-Processing

---



---



"""

#making everything lowercase
df['issue'] = df['Issue'].str.lower()
df[['issue']].head()

#remove funky characters
df['issue_punc'] = df['issue'].str.replace('[^A-z ]','',regex=True).str.replace(' +',' ',regex=True).str.strip()
df[['issue', 'issue_punc']].head()

#tokenization
from nltk.tokenize import sent_tokenize, word_tokenize
df['issue_punc_tok'] = df['issue_punc'].apply(lambda x: word_tokenize(x))
df[['issue_punc', 'issue_punc_tok']].head()

#Stopword removal
nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('english')
stopwords.insert(0, "xxxx")
stopwords.insert(0, "xxxxxxxx")
df['issue_punc_tok_sw'] = df['issue_punc_tok'].apply(lambda tokens: [word for word in tokens if word not in stopwords])
df[['issue_punc_tok', 'issue_punc_tok_sw']].head()

#Lemmatization
nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
df['issue_punc_tok_sw_lemma'] = df['issue_punc_tok_sw'].apply(lambda tokens: [lemmatizer.lemmatize(word) for word in tokens])

# Print the dataframe with lemmatized tokens
df[['issue_punc_tok_sw', 'issue_punc_tok_sw_lemma']].head()

#Repeating the text preparation process for 'Consumer complaint narrative'

#Making everything lowercase
df['Consumer complaint narrative'] = df['Consumer complaint narrative'].str.lower()

#Removing funky characters
df['Complaint_nopunct'] = df['Consumer complaint narrative'].str.replace('[^A-z ]','',regex=True).str.replace(' +',' ',regex=True).str.strip()

#Tokenization
from nltk.tokenize import sent_tokenize, word_tokenize
df['Complaint_nopunct_token'] = df['Complaint_nopunct'].apply(lambda x: word_tokenize(x))

#Stopword removal
df['Complaint_nopunct_token_stop'] = df['Complaint_nopunct_token'].apply(lambda tokens: [word for word in tokens if word not in stopwords])

#Lemmatization
df['Complaint_nopunct_token_stop_lem'] = df['Complaint_nopunct_token_stop'].apply(lambda tokens: [lemmatizer.lemmatize(word) for word in tokens])
df['Complaint_nopunct_token_stop_lem'].head()

#Repeating the text preparation process for 'Company public response'

#Making everything lowercase
df['Company public response'] = df['Company public response'].str.lower()

#Removing funky characters
df['Response_nopunct'] = df['Company public response'].str.replace('[^A-z ]','',regex=True).str.replace(' +',' ',regex=True).str.strip()

#Tokenization
from nltk.tokenize import sent_tokenize, word_tokenize
df['Response_nopunct_token'] = df['Response_nopunct'].apply(lambda x: word_tokenize(x))

#Stopword removal
df['Response_nopunct_token_stop'] = df['Response_nopunct_token'].apply(lambda tokens: [word for word in tokens if word not in stopwords])

#Lemmatization
df['Response_nopunct_token_stop_lem'] = df['Response_nopunct_token_stop'].apply(lambda tokens: [lemmatizer.lemmatize(word) for word in tokens])
df['Response_nopunct_token_stop_lem'].head()

"""Word Embeddings (optional)



---



---


"""

#importing packages
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
import sklearn
from scipy import spatial
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

# using GloVe (Global Vectors) word embeddings by Stanford, obtain the word embedding
!wget --no-check-certificate \
     http://nlp.stanford.edu/data/glove.6B.zip \
     -O /tmp/glove.6B.zip

# extract them into a temporary folder.
import os
import zipfile
with zipfile.ZipFile('/tmp/glove.6B.zip', 'r') as zip_ref:
    zip_ref.extractall('/tmp/glove')

#create dictionary called embeddings_index and append pretrained glove embeddings
import numpy as np
embeddings_index = {}
f = open('/tmp/glove/glove.6B.100d.txt')

for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print('Found %s word vectors.' % len(embeddings_index))
def find_closest_embeddings(embedding):
    return sorted(embeddings_index.keys(), key=lambda word: spatial.distance.euclidean(embeddings_index[word], embedding))

#Using GloVe embeddings to encode data
X = df['Complaint_nopunct_token_stop_lem']
y = df['Response_nopunct_token_stop_lem']
from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test = train_test_split(X, y , test_size = 0.20)

#Finding the number of products
n = len(pd.unique(df['Product']))

print("No.of.unique values :",
      n)

"""Step 3: Topic Modeling/Clustering


---



---


"""

#LDA Topic Modeling
import pprint
from gensim import corpora
from gensim import models
processed_corpus = df['Complaint_nopunct_token_stop_lem']

#define dictionary
dictionary = corpora.Dictionary(processed_corpus)

#Convert corpus to vectors
bow_corpus = [dictionary.doc2bow(text) for text in processed_corpus]

#Model
##Number of clusters = number of distinct products
lda_model = models.LdaMulticore(corpus=bow_corpus, id2word=dictionary, num_topics=16)
doc_lda = lda_model[bow_corpus]

#Getting clusters (print top 5-10 keywords for each cluster)
pprint.pprint(lda_model.print_topics(num_words=5))
print(dictionary)

#Testing the clustering
doc_lda = lda_model[bow_corpus]
for t, doc in zip(X[:3], doc_lda[:3]):
    pprint.pprint((t, doc))

processed_corpus2 = df['Response_nopunct_token_stop_lem']

#define dictionary
dictionary2 = corpora.Dictionary(processed_corpus)

#Convert corpus to vectors
bow_corpus2 = [dictionary2.doc2bow(text) for text in processed_corpus2]

#Model
lda_model2 = models.LdaMulticore(corpus=bow_corpus2, id2word=dictionary2, num_topics=16)
doc_lda2 = lda_model[bow_corpus2]

#Getting clusters (print top 5-10 keywords for each cluster)
pprint.pprint(lda_model2.print_topics(num_words=5))
print(dictionary2)

#Testing the clustering
doc_lda = lda_model[bow_corpus]
for t, doc in zip(y[:3], doc_lda[:3]):
    pprint.pprint((t, doc))

# Commented out IPython magic to ensure Python compatibility.
#Complaint LDA Topic Visualization
#%pip install gensim
from gensim import corpora, models
# %pip install pyLDAvis
import pyLDAvis.gensim_models
dictionary = corpora.Dictionary(df['Complaint_nopunct_token_stop_lem'])
corpus = [dictionary.doc2bow(tokens) for tokens in df['Complaint_nopunct_token_stop_lem']]
num_topics = 5
lda_model = models.LdaModel(corpus = corpus, id2word=dictionary, num_topics=num_topics)

#Complaint LDA Topic Visualization
from pyLDAvis import gensim
!pip install pandas
!pip install --upgrade pandas
vis_data = pyLDAvis.gensim_models.prepare(lda_model, corpus, dictionary)
pyLDAvis.display(vis_data)

#Response LDA Topic Visualization
dictionary2 = corpora.Dictionary(df['Response_nopunct_token_stop_lem'])
corpus2 = [dictionary2.doc2bow(tokens) for tokens in df['Response_nopunct_token_stop_lem']]
lda_model2 = models.LdaModel(corpus2, id2word=dictionary2, num_topics=num_topics)
vis_data2 = pyLDAvis.gensim_models.prepare(lda_model2, corpus2, dictionary2, n_jobs=1)
pyLDAvis.display(vis_data2)

#Add code that removes rows in df that don't have a customer complaint narrative, check with df.shape before and after
print(df.shape)
df = df.loc[data['Consumer complaint narrative'] != ""]
print(df.shape)

#Print the distinct products
n = len(pd.unique(df['Product']))

print("No.of.unique values :",
      n)

print(df['Product'].unique())

#Regrouping redundant products
df['Product_reg'] = df['Product']

df['Product_reg'] = df['Product_reg'].replace(['Credit reporting, credit repair services, or other personal consumer reports'], 'Credit reporting')
df['Product_reg'] = df['Product_reg'].replace(['Credit card or prepaid card'], 'Credit card')
df['Product_reg'] = df['Product_reg'].replace(['Checking or savings account'], 'Bank account or service')
df['Product_reg'] = df['Product_reg'].replace(['Money transfers'], 'Money transfer, virtual currency, or money service')

n = len(pd.unique(df['Product_reg']))

print("No.of.unique values :",
      n)

print(df['Product_reg'].unique())

#Classification by issue
!pip uninstall dask
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import lightgbm as lgbm
from sklearn.metrics import recall_score
from sklearn.metrics import mean_squared_error, mean_absolute_error, max_error, explained_variance_score
from sklearn.model_selection import GridSearchCV

!pip install lightgbm==3.2.1
!pip install --upgrade pandas

df['Complaint_joined'] = df['Complaint_nopunct_token_stop_lem'].apply(' '.join)
df['Issue_joined'] = df['issue_punc_tok_sw_lemma'].apply(' '.join)

X = df['Complaint_joined']
Y = df['Issue_joined']

df['Complaint_Missing'] = df['Complaint_joined'].apply(lambda x: int(x.strip() == ''))
df.drop(columns=['Complaint_joined'], inplace=True)

label_encoder = LabelEncoder()
Y_encoded = label_encoder.fit_transform(Y)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y_encoded, test_size=0.2, random_state=42)

tfidf_vec = TfidfVectorizer(dtype=np.float32, sublinear_tf=True, use_idf=True, smooth_idf=True)
X_train_tfidf = tfidf_vec.fit_transform(X_train)
X_test_tfidf = tfidf_vec.transform(X_test)

#param_grid = {
#    'learning_rate': [0.1, 0.01],
#    'n_estimators': [50, 100, 150],
#    'max_depth': [4, 6],
#    'num_leaves': [30, 70],
#    'max_bin': [100, 300],
#}

estimator = lgbm.LGBMClassifier(objective='multiclass', num_class=len(np.unique(Y_encoded)), verbose=-1)

#model = GridSearchCV(estimator=estimator, param_grid=param_grid, cv=3, n_jobs=-1, scoring='accuracy')
#model.fit(X_train_tfidf, Y_train)

#best_params = model.best_params_
#print("Best Parameters:", best_params)

num_classes = len(np.unique(Y_encoded))

reg_alpha_value = 0.01
reg_lambda_value = 0.01

clf_LGBM = lgbm.LGBMClassifier(objective='multiclass', num_class=num_classes, verbose=-1, learning_rate=0.1, max_depth=4, num_leaves=30, n_estimators=150, max_bin=100, reg_alpha=reg_alpha_value, reg_lambda=reg_lambda_value)
clf_LGBM.fit(X_train_tfidf, Y_train, verbose=-1)

predicted_labels = clf_LGBM.predict(X_test_tfidf)

accuracy = (predicted_labels == Y_test).mean()
print(Y_test[0])
print(f"Accuracy: {accuracy}")

recall = recall_score(Y_test, predicted_labels, average='weighted')
print(f"Recall: {recall}")

#print classification for a specific row in data, check that classifications make sense, print list of groups to know which group is which

#Product column text proccessing

#making everything lowercase
df['product'] = df['Product_reg'].str.lower()
#remove funky characters
df['product_punc'] = df['product'].str.replace('[^A-z ]','',regex=True).str.replace(' +',' ',regex=True).str.strip()
#tokenization
from nltk.tokenize import sent_tokenize, word_tokenize
df['product_punc_tok'] = df['product_punc'].apply(lambda x: word_tokenize(x))
#Stopword removal
df['product_punc_tok_sw'] = df['product_punc_tok'].apply(lambda tokens: [word for word in tokens if word not in stopwords])
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
df['product_punc_tok_sw_lemma'] = df['product_punc_tok_sw'].apply(lambda tokens: [lemmatizer.lemmatize(word) for word in tokens])
# Print the dataframe with lemmatized tokens
df[['product_punc_tok_sw', 'product_punc_tok_sw_lemma']].head()

#Classification By Product
df['Complaint_joined'] = df['Complaint_nopunct_token_stop_lem'].apply(' '.join)
df['Product_joined'] = df['product_punc_tok_sw_lemma'].apply(' '.join)

X = df['Complaint_joined']
Y = df['Product_joined']

df['Complaint_Missing'] = df['Complaint_joined'].apply(lambda x: int(x.strip() == ''))
df.drop(columns=['Complaint_joined'], inplace=True)

label_encoder = LabelEncoder()
Y_encoded = label_encoder.fit_transform(Y)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y_encoded, test_size=0.2, random_state=42)

tfidf_vec = TfidfVectorizer(dtype=np.float32, sublinear_tf=True, use_idf=True, smooth_idf=True)
X_train_tfidf = tfidf_vec.fit_transform(X_train)
X_test_tfidf = tfidf_vec.transform(X_test)

num_classes = len(np.unique(Y_encoded))

reg_alpha_value = 0.01
reg_lambda_value = 0.01

clf_LGBM = lgbm.LGBMClassifier(objective='multiclass', num_class=num_classes, verbose=-1, learning_rate=0.2, max_depth=10, num_leaves=80, n_estimators=500, max_bin=2000, reg_alpha=reg_alpha_value, reg_lambda=reg_lambda_value)
clf_LGBM.fit(X_train_tfidf, Y_train, verbose=-1)

predicted_labels = clf_LGBM.predict(X_test_tfidf)

accuracy = (predicted_labels == Y_test).mean()
print(Y_test[0])
print(f"Accuracy: {accuracy}")

recall = recall_score(Y_test, predicted_labels, average='weighted')
print(f"Recall: {recall}")

#print classification for a specific row in data, check that classifications make sense, print list of groups to know which group is which

#Confusion Matrix
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(Y_test, predicted_labels)

conf_matrix_norm = conf_matrix.astype('float') / conf_matrix.sum(axis=1)[:, np.newaxis]

plt.figure(figsize=(10, 8))
plt.imshow(conf_matrix_norm, interpolation='nearest', cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.colorbar()

classes = label_encoder.classes_
plt.xticks(np.arange(len(classes)), classes, rotation=45)
plt.yticks(np.arange(len(classes)), classes)
plt.ylabel("True label")
plt.xlabel("Predicted label")
plt.tight_layout()
plt.show()
